authen/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import mainapp.views

urlpatterns = [
    url(r'^$', mainapp.views.index, name='index'),
    url(r'^index/', mainapp.views.index, name='index'),
    url(r'^mainapp/', include('mainapp.urls')),
    url(r'^admin/', admin.site.urls),
]

mainapp/urls.py
from django.conf.urls import url
import mainapp.views

app_name = 'mainapp'

urlpatterns = [
    url(r'^register/', mainapp.views.register, name='register'),
    url(r'^login/', mainapp.views.user_login, name='user_login'),
    url(r'^logout/', mainapp.views.user_logout, name='user_logout'),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    # additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

mainapp/forms.py
from django import forms
from django.contrib.auth.models import User
from mainapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

mainapp/views.py
from django.shortcuts import render
from mainapp.forms import UserForm, UserProfileInfoForm

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def index(request):
    context = {}
    return render(request, 'mainapp/index.html', context=context)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT IS NOT ACTIVE!')
        else:
            print("!!! invalid login -> " + username + " : " + password)
            return HttpResponse('INVALID USERNAME OR PASSWORD!')
    else:
        return render(request, 'mainapp/login.html', {})


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)  # hash password
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user  # One to One relation

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context = {'user_form': user_form,
               'profile_form': profile_form,
               'registered': registered}
    return render(request, 'mainapp/registration.html', context=context)

templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-link" href="{% url 'index' %}">Home</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'mainapp:user_logout' %}">Logout</a></li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'mainapp:register' %}">Register</a></li>
                <li><a class="navbar-link" href="{% url 'mainapp:user_login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="jumbotron">
    {% block body_block %}
    {% endblock %}
</div>

</body>
</html>

templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block body_block %}

    <h1>AUTH HOME PAGE</h1>
    <img src="{% static 'images/dog_surprize.jpg' %}" alt="image">


{% endblock %}

templates/mainapp/login.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <h1>AUTH LOGIN PAGE</h1>
    <form action="{% url 'mainapp:user_login'  %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" id="username"  placeholder="имя">
        <label for="password">Password:</label>
        <input type="password" name="password" id="password"  placeholder="пароль">
        <input type="submit" value="Логин">
    </form>
{% endblock %}

templates/mainapp/registration.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <h1>AUTH REGISTRATION PAGE</h1>
    {% if registered  %}
        <h2>Thank you for registering!</h2>
    {% else %}
        <h2>Register here</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Сохранить">
        </form>

    {% endif%}

{% endblock %}